[profile.release]
lto = true

[workspace]
members = [
    "java-compilers/common-args",
    "java-compilers/ojavac",
    "java-compilers/oecj",
    "origami-common",
    "oresolve",
    "omake",
    "ojvmd",
    "ojvm-launch",
    "jvmapi",
    "jvmapi-proto",
]
