package net.dblsaiko.origami.ojavac;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;

import javax.tools.JavaCompiler;
import javax.tools.JavaCompiler.CompilationTask;
import javax.tools.ToolProvider;

public class Main {
    public static void main(String[] args) {
        int optionsLen = Integer.parseInt(args[args.length - 3]);
        int compilationUnitsLen = Integer.parseInt(args[args.length - 2]);
        String manifestPath = args[args.length - 1];

        JavaCompiler systemJavaCompiler = ToolProvider.getSystemJavaCompiler();
        TrackingJavaFileManager fm = new TrackingJavaFileManager(
            systemJavaCompiler.getStandardFileManager(null, null, StandardCharsets.UTF_8)
        );

        CompilationTask task = systemJavaCompiler.getTask(
            null,
            fm,
            null,
            SliceIter.of(args, 0, optionsLen),
            null,
            fm.getJavaFileObjectsFromPaths(Arrays.stream(args, optionsLen, optionsLen + compilationUnitsLen).map(Path::of).toList())
        );

        boolean result = task.call();

        if (!result) {
            System.exit(1);
        }

        if (!manifestPath.isBlank()) {
            writeManifest(SliceIter.of(args, optionsLen, optionsLen + compilationUnitsLen), fm, Path.of(manifestPath));
        }
    }

    private static void writeManifest(Iterable<String> files, TrackingJavaFileManager fm, Path manifestPath) {
        try (PrintWriter pw = new PrintWriter(Files.newBufferedWriter(manifestPath))) {
            pw.println("; Origami Manifest");
            pw.print("; Autogenerated file for classes");

            for (String s : files) {
                pw.printf(" '%s'", s);
            }

            pw.println();
            pw.println("; Do not edit.");

            if (!fm.getInputFiles().isEmpty()) {
                pw.println();
                pw.println("; Inputs");

                for (Path inputFile : fm.getInputFiles()) {
                    pw.printf("<- %s\n", inputFile);
                }
            }

            if (!fm.getOutputFiles().isEmpty()) {
                pw.println();
                pw.println("; Outputs");

                for (Path outputFile : fm.getOutputFiles()) {
                    pw.printf("-> %s\n", outputFile);
                }
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
